### ISSUE TITLE
Error pulling sampleevents for Madagascar

### ISSUE THREAD

**Issue by jpwrobinson** [data-mermaid/mermaidr#13]
Hi - amazing package! Just started working with it and very impressed.

I'm trying to get transect-level fish biomass estimates for the Madagascar project (Madagascar WCS MACMON 2015-6). If I  run:

```
my_projects <- mermaid_get_my_projects()
proj <- my_projects %>%  filter(name == "Madagascar WCS MACMON 2015-6")
proj %>%  mermaid_get_project_data(method = "fishbelt", data = "sampleunits") 
```

This returns one biomass estimate per site. I would expect 'sampleunits' to return biomass per transect per site (e.g. multiple rows for each site). In this output, the transect numbers vary from 2 - 26, but there is only one transect number per site (except site = Kisimani_16 which has 2 transects). 

Also, if I run:
 
`proj %>%  mermaid_get_project_data(method = "fishbelt", data = "sampleevents") `

I get API request Gateway Timeout (504). So is 'sampleunits' is accessing data for 'sampleevents' here? 

Any ideas how I can get transect-level biomass estimates?

Both sampleunits and sampleevents work fine for `method = 'benthicpit'`, but I also couldn't access `method = 'habitatcomplexity'`, which returned 0 rows. Is that complexity data available in this project?

Thanks!

**Comment by jpwrobinson** [comment]
I've just realised there may only be 1 transect per site in this dataset. Can I check that? The API timeout for 'sampleevents' still makes me think something may be broken.

**Comment by sharlagelfand** [comment]
Hey @jpwrobinson! Thanks for trying out the package and for the kind words - still early days on it, so it's super helpful to have people try it out and identify issues!

Looking at things one at a time...

It does indeed look like there's mostly 1 transect per site in this data. You could check this by counting the number of distinct transects for each site:

```r
library(mermaidr)
library(dplyr)

my_projects <- mermaid_get_my_projects()

proj <- my_projects %>%
  filter(name == "Madagascar WCS MACMON 2015-6")

sus <- proj %>%
  mermaid_get_project_data(method = "fishbelt", data = "sampleunits")

transects_per_site <- sus %>%
  group_by(site) %>%
  summarise(
    n_transects = n_distinct(transect_number),
    .groups = "drop"
  )

transects_per_site %>%
  count(n_transects)
# # A tibble: 2 x 2
# n_transects     n
#       <int> <int>
# 1         1    67
# 2         2     5
```

So it looks like there's 67 sites with 1 transect, and 5 with 2:

```r
transects_per_site %>%
  filter(n_transects == 2)
# # A tibble: 5 x 2
# site        n_transects
# <chr>             <int>
# 1 Kisimani_16         2
# 2 NF01                2
# 3 NK01                2
# 4 NS01                2
# 5 NT01                2
```

You can see this looking at the observations too, if that's easier to make sense of (removing the factor of "what aggregation is actually happening in sampleunits?"):

```r
obs <- proj %>%
  mermaid_get_project_data(method = "fishbelt", data = "observations")

obs %>%
  group_by(site) %>%
  summarise(
    n_transects = n_distinct(transect_number),
    .groups = "drop"
  ) %>%
  count(n_transects)
# # A tibble: 2 x 2
# n_transects     n
#       <int> <int>
# 1         1    67
# 2         2     5
```

So for the 5 sites that do have 2 transects, you do see `sampleunits` returns biomass per transect per site (just adding some random noise to the data since it's private):

```r
transects_per_site %>%
  filter(n_transects == 2) %>%
  inner_join(sus, by = "site") %>%
  select(site, transect_number, biomass_kgha) %>%
  mutate(biomass_kgha = biomass_kgha * rnorm(1))
# # A tibble: 10 x 3
# site        transect_number biomass_kgha
# <chr>                 <int>        <dbl>
# 1 Kisimani_16             1        791. 
# 2 Kisimani_16             2       1574. 
# 3 NF01                    1        306. 
# 4 NF01                    2        212. 
# 5 NK01                    1        549. 
# 6 NK01                    2        310. 
# 7 NS01                    1        366. 
# 8 NS01                    2         91.7
# 9 NT01                    1       1766. 
# 10 NT01                   2       1785. 
```

I hope that clarifies things on that! Re: the transects being numbered from 2 - 26, you can see above that it does look like there's some numbering being added to the sites - I'm not too familiar with this project or the data entry conventions on it, but some cases do look like the transect number has just been added to the site name, e.g.:

```r
sus %>%
  select(site, transect_number)
# # A tibble: 77 x 2
# site            transect_number
# <chr>                     <int>
# 1 Ambarinidada_11            11
# 2 Ambato_04                   4
# 3 Ambato_05                   5
# 4 Ambatofisaka_19            19
# 5 Ambatomilay_18             18
# 6 Amparimilay_10             10
# 7 Andra_06                    1
# 8 Andravona_08                1
# 9 Andravona_12                1
# 10 Andre_07                   1
# # … with 67 more rows
```

Which sounds like it's not the usual way of naming sites - maybe e.g. Ambato_04 and Ambato_05 should actually just be the same site "Ambato", but that might account for why you're only seeing one transect per site in most cases? @emilydarling do you have thoughts on this data entry and if it needs some ironing out?

Re: `sampleevents` erroring - that's definitely an issue with the API timing out on our end, something that needs fixing. I'll provide an update once I have one on that.

Finally, for 'habitatcomplexity' data, if you look in Collect for this project and filter for habitat complexity (here: https://collect.datamermaid.org/#/projects/4080679f-1145-4d13-8afb-c2f694004f97/transectmethods) you can see there's no habitat complexity data for this project:

<img width="1453" alt="Screen Shot 2021-01-08 at 4 53 50 PM" src="https://user-images.githubusercontent.com/15895337/104068024-3343de80-51d2-11eb-94db-3503e1c47596.png">

So that's why the API doesn't return anything.

Hope that's helpful - let me know if you have more questions!

**Comment by jpwrobinson** [comment]
Thanks Sharla! That all makes sense to me. Looks like site names could be cleaned to better represent the sampling hierarchy. This works fine for my purposes though!

**Comment by sharlagelfand** [comment]
Great, happy to help! I'll keep this issue open as a reminder for myself on the `sampleeevents` stuff - will check in once that's fixed.

**Comment by sharlagelfand** [comment]
Hi @jpwrobinson, happy to say I have an update for you!

We've made improvements to the API performance, so you shouldn't experience timeouts or errors querying sampleevents anymore:

```r
library(mermaidr)
library(dplyr)

my_projects <- mermaid_get_my_projects()

proj <- my_projects %>%
  filter(name == "Madagascar WCS MACMON 2015-6")

ses <- proj %>%
  mermaid_get_project_data(method = "fishbelt", data = "sampleevents")

head(ses)
# # A tibble: 6 x 34
# project   tags  country site  latitude longitude reef_type reef_zone
# <chr>     <chr> <chr>   <chr>    <dbl>     <dbl> <chr>     <chr>    
# 1 Madaga… WCS … Madaga… Amba…    -12.9      48.6 fringing  fore reef
# 2 Madaga… WCS … Madaga… Amba…    -16.6      49.8 fringing  fore reef
# 3 Madaga… WCS … Madaga… Amba…    -16.6      49.8 fringing  fore reef
# 4 Madaga… WCS … Madaga… Amba…    -13.6      47.8 patch     fore reef
# 5 Madaga… WCS … Madaga… Amba…    -13.6      47.8 patch     fore reef
# 6 Madaga… WCS … Madaga… Ampa…    -12.9      48.6 fringing  fore reef
```

(plus a ton more columns, but not shown for brevity!)

Please let me know if you continue to experience issues - thanks!
