### ISSUE TITLE
Emily first run-through

### ISSUE THREAD

**Issue by esdarling** [data-mermaid/mermaidr#2]
Looking so awesome and will revolutionize my life. A few suggestions:

- [x] mermaid_list_my_projects(): countries stored as a list isn't super useful (i'm terrible with lists). Any options to compress into character column? There might be more than 1 country, but often should only be one.

- [x] Out of curiosity, why is mermaid_search_projects(country = "Tanzania" not returning a project? Could country be stored as Republic of Tanzania, maybe? If so, we should think about trying to rename some countries in the backend so they're more obvious for users. 
 

- [x] With get_endpoints, limit is useful. But how do I get all endpoints if there' more than 50? 

- [x] mermaid_get_endpoint("managements") could be renamed to mermaid_get_endpoint("management"); not plural

- [x] add help for devtools newbies, library(mermaidr) would be helpful after the devtools install

**Comment by sharlagelfand** [comment]
Listing the other things we discussed on Skype to keep track of:

[ ] Enable getting endpoints for multiple/"all my" projects
[ ] Test project flag for filtering out

**Comment by esdarling** [comment]
Also, 

- [ ] Management parties - NAs coming down as NULL (should be NA) 
- [ ] Tags is another list example, which ideally is collapsed to a vector and renamed as organization (see comments in sample event column reorder)

**Comment by esdarling** [comment]
Here's what I think is a useful order and column selection for beltfish sample event endpoints tibble:

tanz_belfish_sample_event <- mermaid_search_projects("Tanzania Vibrant Oceans 2019") %>% 
  mermaid_get_project_endpoint("beltfishes/sampleevents", limit = 5)

tanz_belfish_sample_event %>% 
  select(project_name, 
         #tags, #collapse to character vector not list
         country_name, 
         site_name, 
         latitude, 
         longitude, 
         reef_type, 
         reef_zone, 
         reef_exposure, 
         management_name:management_rules, 
         sample_date, 
         biomass_kgha_avg, 
         biomass_kgha_by_trophic_group_avg, #separate columns for each trophic group
         data_policy_beltfish, 
         contains("_notes"), 
         contact_link) %>%
  rename("country" = country_name, 
         #"organization" = tags, 
         "site" = site_name)

**Comment by esdarling** [comment]
For sample unit: 

tanz_belfish_sample_unit <- mermaid_search_projects("Tanzania Vibrant Oceans 2019") %>% 
  mermaid_get_project_endpoint("beltfishes/sampleunits", limit = 5)

tanz_belfish_sample_unit %>% 
  select(project_name, 
         #tags, #collapse to character vector
         country_name, 
         site_name, 
         latitude, 
         longitude, 
         reef_type, 
         reef_zone, 
         reef_exposure, 
         reef_slope,
         #tide, #missing from API? 
         #current, #missing from API? 
         #visibility, #missing from API? 
         management_name:management_rules, 
         sample_date, 
         number, 
         size_bin, 
         transect_len_surveyed, 
         #transect_width, #need transect width - is that on API call? 
         biomass_kgha, 
         biomass_kgha_by_trophic_group, #separate columns for each trophic
         data_policy_beltfish, 
         contains("_notes"), #is there a sample unit notes as well? only see site and mgmt
         contact_link) %>%
  rename("country" = country_name, 
         #"organization" = tags, 
         "site" = site_name, 
         "transect_number" = number)

**Comment by sharlagelfand** [comment]
Just providing some updates of where things are at:

> mermaid_list_my_projects(): countries stored as a list isn't super useful (i'm terrible with lists). Any options to compress into character column? There might be more than 1 country, but often should only be one.

`countries` and `tags` are now semicolon separated into a character column. Not comma separated because some countries have commas in their names, e.g. Tanzania is actually named "Tanzania, United Republic of". Speaking of...

> Out of curiosity, why is mermaid_search_projects(country = "Tanzania" not returning a project? Could country be stored as Republic of Tanzania, maybe? If so, we should think about trying to rename some countries in the backend so they're more obvious for users.

Rather than renaming I changed the search to search whether the `countries` field contains country, instead of being exactly it. So searching country = "Tanzania" will return records where countries is "Tanzania, United Republic of". I also made a utility function `mermaid_countries()` that lists all countries in case you're not sure what a country is named (e.g. Vietnam is under Viet Nam, so lookup may be helpful)

> With get_endpoints, limit is useful. But how do I get all endpoints if there' more than 50?

I changed the `limit` field on everything to be NULL, which means it will now get *all* records by default. If you want less, specify limit (whatever value you want). This is probably a more useful default because I don't forsee many cases where you *don't* want all your data!

> mermaid_get_endpoint("managements") could be renamed to mermaid_get_endpoint("management"); not plural

This is a list of all managements in MERMAID, not for a specific project - I think the pluralizing makes sense in that case

> Test project flag for filtering out

Test projects are now excluded by default in `mermaid_list_projects()`, `mermaid_list_my_projects()`, `mermaid_search_projects()` -  if you want to include them, set `include_test_projects = TRUE`

I also recoded the `status` and `data_policy_*` fields in the project lists to be actual values (i.e., Locked, Test, Open for status, and Private, Public Summary, Public for the data policies) to be more clear/useful to users than just number codes

The README and examples have been updated to demonstrate all (hopefully) of these

Anything not mentioned is to come - some things may be addressed by `mermaidreporting` instead but I'll discuss those as I get through them.

**Comment by sharlagelfand** [comment]
Oh also @esdarling - re:

> Management parties - NAs coming down as NULL (should be NA)

Not sure where you're seeing this - can you show the function/output of what you mean so I can look into it? Thanks!

**Comment by sharlagelfand** [comment]
Updated now to enable getting data from multiple projects (and multiple endpoints, if you so choose)! Details in the README and should "just work" but let me know if there's any issues!

For the new endpoints, the columns *should* be mostly what you expect now Emily, Kim has done some reconfiguring of the API and I've done some renaming/reordering. The "should" and "mostly" is on my end re: renaming things. 

I've kept the trophic group column as a single column for now, since `mermaidreporting` will handle it as a single column, and I'll build in a utility function to make for easy conversion of it to multiple columns and easy creation of a summary table.

**Comment by esdarling** [comment]
Been working through the new edits, so cool! 

On the clean endpoints, a few minor things (and oversights on my end!) 

- [ ] Drop project_id from all 3 clean endpoint files; unless we need to keep it for any code functions? 

- [ ] fish_obs has 2 columns named "project_id" which isn't making dplyr::select happy. Drop both :) And see below for how I think columns can be selected and reordered. 

- [ ] I messed up and forgot that we need DEPTH for all 3 of the clean endpoint files. Is that in the API? I see it in the fish_obs, is there a depth in the sampleunit and sampleevent? If so, we need it - can go before transect_number

- [ ] In all 3 clean endpoints, rename "transect_len_surveyed"  to "transect_length"       

- [ ] Can we drop "_name" from any column names, shouldn't need that distinction now that _id is dropped from all tibbles. These columns should then all be just the first string, with the exception of management_secondary: 
[1] "project_name"              "country_name"              "site_name"                
[4] "tide_name"                 "current_name"              "visibility_name"          
[7] "management_name"           "management_name_secondary" 

- [ ] can you check there's no ID-like items in the "tags" column? Would just want the tag names in the column.

- [ ] agree that using trophic_group biomass columns as more 'normal' columns would be good in the summary tables for sampleunit and sampleevent tables

- [ ] for Fish obs, can we reorder to only these columns? 
"project_name" #see note above re: removing all "_name"
"tags"
"country_name" 
"site_name"   
"latitude"                 
"longitude"
"reef_type"                
"reef_zone"                
"reef_exposure"   
"reef_slope"
tide
current
visibility,     
"management_name"          
"management_name_secondary" 
"management_est_year"      
"management_size"           
"management_parties"        
"management_compliance"    
"management_rules"          
"sample_date"
"sample_time"
"transect_len_surveyed"   #rename to transect_length               
"transect_width" 
"size_bin"       
"observers"
"depth" 
"transect_number" 
"label" 
"fish_family"              
"fish_genus"
"fish_taxon"
 "size"
"count      
"biomass_constant_a"        "biomass_constant_b"        "biomass_constant_c"
 "biomass_kgha"
 "trophic_group"            
"trophic_level"             "functional_group"          "vulnerability"            
"data_policy_beltfish"
contains("notes")
contact_link

**Comment by sharlagelfand** [comment]
@esdarling most of the changes above should be addressed now! there are some changes (e.g. adding depth in) that are in dev MERMAID only and so they'll be addressed in the main package branch once they're in production. I'll provide an update then :)
