### ISSUE TITLE
Add multiple search strings? 

### ISSUE THREAD

**Issue by esdarling** [data-mermaid/mermaidr#3]
Is there a way to support multiple search strings? I.e., for country and tag, like: 

mermaid_search_projects(tag = "Vibrant Oceans" &  country = "Indonesia", 
                                         token = mermaid_token())

Currently, doesn't seem to like that: 
![Screen Shot 2020-04-11 at 9 48 46 AM](https://user-images.githubusercontent.com/3466848/79045541-aa176100-7bd9-11ea-9ada-f930a02d2682.png)

**Comment by saanobhaai** [comment]
For what it's worth, my $0.02 on this: there should be, in packages that use the MERMAID API:

  *   a layer (i.e. a group of methods available at some level) which map fairly closely to what the API offers in terms of filtering, searching, sorting, and pagination. Might be worth going over what that is; proper documentation is on my list but a big job.
  *   another layer that maps the lower-level layer onto higher-level functions convenience utilities for producing commonly needed outputs

...so that a user can, after installing the package, access the API at higher level for commonly needed things, or use the lower-level layer for customization. The API supports requests for multiple tags, multiple countries, and so on, in any combination -- my understanding is that mermaidr is downloading and then doing its own internal filtering, which is fine, but might be worth staying closer to the API (similar to the way transect aggregation happens on the API side).

Best,
Kim

[WCS logo]

Kim Fisher
Spatial Analyst and Developer
Wildlife Conservation Society
kfisher@wcs.org<mailto:kfisher@wcs.org>
welikia.org<https://welikia.org/> | visionmaker.nyc<https://visionmaker.nyc/> | datamermaid.org<https://datamermaid.org/>
skype: wcs.org_kfisher | calendar<https://calendly.com/kimfisher>



________________________________

**Comment by sharlagelfand** [comment]
Sorry @esdarling @saanobhaai, just seeing this now!

Right now you can filter by both country and tag, but separating by comma (as these are separate function arguments):

``` r
library(mermaidr)

mermaid_search_projects(tag = "Vibrant Oceans", country = "Indonesia")
#> # A tibble: 3 x 14
#>   id    name  countries num_sites tags  notes status data_policy_bel…
#>   <chr> <chr> <chr>         <int> <chr> <chr> <chr>  <chr>           
#> 1 3a9e… Aceh… Indonesia        18 WCS … ""    Open   Private         
#> 2 507d… Kari… Indonesia        43 WCS … ""    Open   Public Summary  
#> 3 bcb1… Taka… Indonesia        39 WCS … ""    Open   Private         
#> # … with 6 more variables: data_policy_benthiclit <chr>,
#> #   data_policy_benthicpit <chr>, data_policy_habitatcomplexity <chr>,
#> #   data_policy_bleachingqc <chr>, created_on <chr>, updated_on <chr>
```

Right now, for projects (above), `mermaidr` is using the API's filtering.

Any other filtering has to be done afterwards using dplyr verbs and isn't part of `mermaidr`:

``` r
library(mermaidr)
library(dplyr)

mermaid_list_my_projects() %>%
  mermaid_get_project_endpoint("sites") %>%
  filter(reef_type == "fringing")  # dplyr filter command

#> # A tibble: 81 x 13
#> project id    name  notes latitude longitude country
#> <chr>   <chr> <chr> <chr>    <dbl>     <dbl> <chr>  
#>   1 2017_K… f2c8… KD2   ""       -17.3      179. Fiji   
#> 2 2017_K… 1536… KD3   ""       -17.4      179. Fiji   
#> 3 2017_K… 2a05… MD1   ""       -17.4      179. Fiji   
#> 4 2017_K… 2f3f… MD4   ""       -17.4      179. Fiji   
#> 5 2017_K… 2df1… MD6   ""       -17.4      179. Fiji   
#> 6 2017_K… dc16… NC1   ""       -17.2      179. Fiji   
#> 7 2017_K… 7a77… NC2   ""       -17.3      179. Fiji   
#> 8 2017_K… b31c… NF1   ""       -17.4      179. Fiji   
#> 9 2017_K… 33da… NF3   ""       -17.4      179. Fiji   
#> 10 2017_K… 87df… NF4   ""       -17.4      179. Fiji   
#> # … with 71 more rows, and 6 more variables: reef_type <chr>,
#> #   reef_zone <chr>, exposure <chr>, predecessor <lgl>,
#> #   created_on <chr>, updated_on <chr>
```

Happy to talk about further filtering and taking advantage of what the API already offers
