### ISSUE TITLE
Add prod/dev switching to documentation

### ISSUE THREAD

**Issue by esdarling** [data-mermaid/mermaidr#32]
Hi Sharla, could you add a note to the documentation (maybe get_project_data) function on how to access dev-collect data? I remember you showing me this once but have lost where this code is, and think it would be helpful to add and landmark into the documentation, if possible. Thanks!

**Comment by sharlagelfand** [comment]
@esdarling Added a vignette here! https://data-mermaid.github.io/mermaidr/articles/articles/accessing_dev_collect_data.html

I would like to improve this workflow at some point so that you don't have to install from different branches, but it's a bit tricky with the authorization token and I haven't found the time yet - hopefully this is clear enough for now! Let me know if you want any updates on the wording or if it's not clear.

Thanks!
