### ISSUE TITLE
Add error message to bleaching import perc cover != integer

### ISSUE THREAD

**Issue by esdarling** [data-mermaid/mermaidr#41]
Issue for bleaching ingest is that the three percent cover columns will only accept integer values but it will be a common error for people to upload numeric values. 
`Hard coral % cover`, 
`Soft coral % cover`
`Macroalgae % cover`

Add an error message to mermaid_import_project_data function when method == bleaching and any perc cover column != integer, 
"WARNING: Your percent cover estimates are not integers and may have uploaded as NAs" 

@saanobhaai -- can we add an error in MERMAID that prevents perc cover numerics from uploading at all, or rounds them into an integer automatically?

**Comment by esdarling** [comment]
![Screen Shot 2021-12-14 at 1 26 55 PM](https://user-images.githubusercontent.com/3466848/146059303-381d73c6-74fc-4204-873f-86666a8da586.png)
![Screen Shot 2021-12-14 at 1 27 04 PM](https://user-images.githubusercontent.com/3466848/146059304-4a487006-792e-4b69-8792-1ad510cf8091.png)

**Comment by saanobhaai** [comment]
@esdarling -- Alternatively, we could make these `Decimal` fields, and accept more precision -- though that seems misleading given the protocol.

Otherwise -- would you rather round (coerce to nearest int), or give an error? Either is possible. I guess I would recommend the latter, because then there would be no disparity between the ingest csv and the ingested MERMAID results.

**Comment by sharlagelfand** [comment]
@esdarling @saanobhaai If this is something that can be handled on the API side I think that would be more consistent with how things are so far - e.g. to Kim's suggestion that it would error if the values are not all integers, and mermaidr would just return those errors as it does with others (rather than custom checking + errorring on the R side)
